writables:
  - app/cache

build:
  - apt-get update -y
  - apt-get -y install memcached php5-memcache
  - composer install --no-interaction --ansi --no-progress
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - yes | php app/console doctrine:fixtures:load --no-interaction
  - php app/console assets:install --symlink web
  - php app/console cache:clear --env=prod
  - php app/console assetic:dump --env=prod
  - php app/console parse --limit=100
