parameters:
#    babouma_feed.example.class: Babouma\FeedBundle\Example

services:
#    babouma_feed.example:
#        class: %babouma_feed.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
