fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile_show:
    pattern: /profile
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /settings
        permanent: true

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /settings

FeederateFeederateBundle_User:
    resource: "@FeederateFeederateBundle/Controller/UserController.php"
    prefix: api
    type: rest
    options:
        expose: true

FeederateFeederateBundle_Feed:
    resource: "@FeederateFeederateBundle/Controller/FeedController.php"
    prefix: api
    type: rest
    options:
        expose: true

FeederateFeederateBundle_Entry:
    resource: "@FeederateFeederateBundle/Controller/EntryController.php"
    prefix: api
    type: rest
    options:
        expose: true

FeederateFeederateBundle_Summary:
    resource: "@FeederateFeederateBundle/Controller/SummaryController.php"
    prefix: api
    type: rest
    options:
        expose: true

FeederateFeederateBundle_Front:
    resource: "@FeederateFeederateBundle/Controller/FrontController.php"
    type: annotation

FeederateFeederateBundle_Settings:
    resource: "@FeederateFeederateBundle/Controller/SettingsController.php"
    type: annotation

FeederateFeederateBundle_Admin:
    resource: "@FeederateFeederateBundle/Controller/AdminController.php"
    type: annotation
