parameters:
    feederate.parser.command.class: Feederate\FeederateBundle\Command\ParserCommand

services:
    feederate.parser.command:
        class: %feederate.parser.command.class%
        calls:
            - [ setContainer, ['@service_container']]
